spring.application.name=oscar-voting-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/oscar_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:1234}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#server.port=${PORT:8080}
#
##spring.data.redis.host=${REDIS_HOST:localhost}
##spring.data.redis.port=${REDIS_PORT:6379}
##spring.data.redis.password=${REDIS_PASSWORD:password}
##spring.data.redis.username=${REDIS_HOST}
#
## Use o valor completo que aparece no campo "Internal Key Value URL" do Render
#spring.data.redis.url=redis://red-d6smialm5p6s73atsk90:DNrWI9dntThVVayjJYan5IlFrLMfcziB@red-d6smialm5p6s73atsk90:6379
#

spring.cache.type=redis
spring.cache.cache-names=user_vote,users